### ISSUE TITLE
[1.21.1] Plugin fails to enable: NoClassDefFoundError for CraftServer (v1_21_R1)

### ISSUE THREAD

**Issue by Blacklaegend** [andrei1058/BedWars1058#1143]
Environment:  
• Failed environment: Paper 1.21.1 (build 133) + BedWars1058 v25.5-SNAPSHOT → crashes  
﻿
• Working environment: Paper 1.21.4 + BedWars1058 v25.5-SNAPSHOT → works correctly  
﻿
• Modrinth version: v25.3 (broken on 1.21.4, user previously reported bugs)  
﻿
• Java: OpenJDK 21.0.11  
﻿
• OS: Windows 11  
﻿
Bug 1: Plugin fails to enable on Paper 1.21.1
﻿
There are some logs about this bug.
﻿
[12:20:58 INFO]: Loading server plugin BedWars1058 v25.5-SNAPSHOT
[12:20:58 INFO]: Loading support for Paper 1.21.1
...
[12:21:10 INFO]: Enabling BedWars1058 v25.5-SNAPSHOT
[12:21:10 ERROR]: Error occurred while enabling BedWars1058 v25.5-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R1/CraftServer
at bedwars-plugin-25.5-SNAPSHOT.jar/com.andrei1058.bedwars.platform.paper.v1_21_R1_NMS.registerCommand(v1_21_R1_NMS.java:51)
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R1.CraftServer
﻿
﻿
Expected behavior: Plugin should load normally on Paper 1.21.1, just as it does on 1.21.4.
﻿
Actual behavior: NoClassDefFoundError for v1_21_R1.CraftServer. The jar seems to be compiled for 1.21.4 (NMS v1_21_R3) and lacks the 1.21.1 NMS adapter. This prevents the entire BedWars1058 ecosystem (including 233BedWars and Compass) from working on 1.21.1.
﻿
Note: The same v25.5 jar works perfectly on Paper 1.21.4, confirming the issue is version-specific.
﻿
Bug 2: Modrinth release v25.3 is broken on 1.21.4 – v25.5 required
﻿
The official Modrinth page currently lists v25.3 as the latest stable release for 1.21.4. However, version 25.5 runs relatively well in Minecraft 1.21.4.
﻿
Request: Please update the Modrinth release to v25.5 (or a newer stable build) so users can download a working version directly. Alternatively, add a clear notice that v25.3 is outdated and link to the correct build.
﻿
